### ISSUE TITLE
Ausgaben Foto Attribut (View)

### ISSUE THREAD

**Issue by DannieKr** [Rexo99/MoneyMate#12]
* Ausgaben View erweitern um Foto hinzufügen zu können

**Comment by DoriZim** [comment]
Fotos können gemacht werden und theoretisch weitergeleitet werden, damit man sie abspeichern kann.
Kamera Controller wird aber nicht richtig disposed

**Comment by DoriZim** [comment]
Camera Controller funktioniert und kann implementiert werden

**Comment by DannieKr** [comment]
Kannst du es so machen, dass die Bilder einfach in der Galerie abgespeichert werden? Wenn man der Ausgabe ein Bild hinzufügen möchte öffnet sich halt einfach die Galerie und dann kann man ein Foto aussuchen.

**Comment by DoriZim** [comment]
Fänd es dann unnötig, die Kamera in der App zu haben.

Ich würde es besser finden wenn der User entweder ein vorhandenes Bild aus der Galerie aussucht oder eben eins in der App macht, welches automatisch eingefügt wird.

Macht man in der App ein Bild, wird der Pfad automatisch mitgespeichert, also kannst du es einfach von da aufrufen

@DannieKr
