### ISSUE TITLE
HomePage not refreshing upon account change

### ISSUE THREAD

**Issue by DoriZim** [Rexo99/MoneyMate#27]
Wenn man eingeloggt ist, sich ausloggt und dann neu registriert dann refreshed die HomePage nicht, also die Values des anderen Accounts bleiben angezeigt.

**Comment by DannieKr** [comment]
@Rexo99 warum hast du das auskommentiert?
![grafik](https://github.com/Rexo99/MoneyMate/assets/72869131/0f71ae6e-bdff-4be9-94f6-a2bc2de83ac2)

**Comment by Rexo99** [comment]
habe es auskommentiert damit expenseList final bleiben kann. Habe es jetzt gefixt in dem ich die clear() auf der Liste aufrufe und nicht neu initialisiere. die List wird bei login() in der Methode initExpenseList() geleert und neu gefüllt. Dementsprechend muss nichts in LogoutUser aufgerufen werden
