### ISSUE TITLE
Auto-Login, wenn keine Internetverbindung besteht

### ISSUE THREAD

**Issue by DoriZim** [Rexo99/MoneyMate#38]
Wenn ein User schonmal eingeloggt war und Auto-Login aktiviert hat, dann wird er auch dann "eingeloggt", wenn keine Internetverbindung besteht -> Problem, da lokal keine Daten gespeichert werden und der User dann ohne Kontext in die App geworfen wird

"Failed to look up hinkelmanns.org" müsste gecatched werden

**Comment by DannieKr** [comment]
fixed

**Comment by DannieKr** [comment]
nvm, bekommen wir nicht mehr gefixt, der fix verursacht nur noch mehr Probleme, das Statemanagement in Login.dart führt so Problemen
