### ISSUE TITLE
Kategorien View

### ISSUE THREAD

**Issue by DannieKr** [Rexo99/MoneyMate#4]
* Übersicht über alle Kategorien
* Kategorien erstellen
* Kategorien bearbeiten
* Kategorien löschen

**Comment by MatttWatson** [comment]
Die wichtigsten Sachen die noch fehlten:
Features: zugehörige Expenses 
                 Status indication des Budgets

Die anderen Sachen haben auch viel Berechtigung doch sind sie leider zeitlich nicht mehr drin
